import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { apiClient, ApiError } from '../api/apiClient';
import { useBookingFlow } from '../context/BookingFlowContext';

export function TravellerPage() { const navigate = useNavigate(); const { quoteId, setBooking } = useBookingFlow(); const [form, setForm] = useState({ firstName: '', lastName: '', dob: '1999-01-01', gender: 'M', email: '', phone: '' }); const [error, setError] = useState('');
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!quoteId) return; try { const result = await apiClient.createBooking({ quoteId, contact: { email: form.email, phone: form.phone }, travellers: [{ type: 'ADULT', title: 'MR', firstName: form.firstName, lastName: form.lastName, dob: form.dob, gender: form.gender }] }); setBooking(result.id, result.bookingReference); navigate('/payment'); } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Booking failed'); } }
  const update = (key: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setForm({ ...form, [key]: event.target.value });
  return <main className="page narrow"><p className="eyebrow">TRAVELLER DETAILS</p><h1>Who is flying?</h1><form className="form-stack" onSubmit={submit}><div className="two-up"><label>First name<input value={form.firstName} onChange={update('firstName')} required /></label><label>Last name<input value={form.lastName} onChange={update('lastName')} required /></label></div><div className="two-up"><label>Date of birth<input type="date" value={form.dob} onChange={update('dob')} required /></label><label>Gender<select value={form.gender} onChange={update('gender')}><option value="M">Male</option><option value="F">Female</option><option value="O">Other</option></select></label></div><label>Email<input type="email" value={form.email} onChange={update('email')} required /></label><label>Phone<input value={form.phone} onChange={update('phone')} required /></label>{error && <p className="error">{error}</p>}<button className="primary">Create booking</button></form></main>; }
